import type { PropsWithChildren } from "hono/jsx";

export function Layout(
  props: PropsWithChildren<{ title: string; repoNav?: { name: string; active?: "summary" | "log" } }>,
) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{props.title}</title>
        <link rel="stylesheet" href="/terminal.min.css" />
        <link rel="stylesheet" href="/cgit.css" />
      </head>
      <body>
        <div class="container">
          <header>
            <div class="terminal-nav">
              <div class="terminal-logo">
                <div class="logo terminal-prompt"><a href="/">cgit-ts</a></div>
              </div>
              {props.repoNav ? (
                <nav class="terminal-menu">
                  <ul>
                    <li>
                      <a class={`menu-item${props.repoNav.active === "summary" ? " active" : ""}`}
                         href={`/${props.repoNav.name}/`}>summary</a>
                    </li>
                    <li>
                      <a class={`menu-item${props.repoNav.active === "log" ? " active" : ""}`}
                         href={`/${props.repoNav.name}/log/`}>log</a>
                    </li>
                  </ul>
                </nav>
              ) : null}
            </div>
          </header>
          <main>{props.children}</main>
          <hr />
          <footer>
            <p>generated by cgit-ts</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
