import type { PropsWithChildren } from "hono/jsx";

export function Layout(props: PropsWithChildren<{ title: string; repoNav?: { name: string } }>) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>{props.title}</title>
        <link rel="stylesheet" href="/cgit.css" />
      </head>
      <body>
        <header class="site-header">
          <a href="/">cgit-ts</a>
          {props.repoNav ? (
            <nav class="repo-nav">
              <a href={`/${props.repoNav.name}/`}>summary</a>
              <a href={`/${props.repoNav.name}/log/`}>log</a>
            </nav>
          ) : null}
        </header>
        <main>{props.children}</main>
        <footer class="site-footer">generated by cgit-ts</footer>
      </body>
    </html>
  );
}
