import { jsxRenderer } from "hono/jsx-renderer";
import type { PropsWithChildren } from "hono/jsx";

export interface RepoNav {
  name: string;
  active: "summary" | "log";
}

// Type the second argument of c.render(content, props) for every handler.
declare module "hono" {
  interface ContextRenderer {
    (content: string | Promise<string>, props?: { repoNav?: RepoNav }): Response;
  }
}

function Header({ repoNav }: { repoNav?: RepoNav }) {
  return (
    <header>
      <div class="terminal-nav">
        <div class="terminal-logo">
          <div class="logo terminal-prompt">
            <a href="/">cgit-ts</a>
          </div>
        </div>
        {repoNav ? (
          <nav class="terminal-menu">
            <ul>
              <li>
                <a
                  class={`menu-item${repoNav.active === "summary" ? " active" : ""}`}
                  href={`/${repoNav.name}/`}
                >
                  summary
                </a>
              </li>
              <li>
                <a
                  class={`menu-item${repoNav.active === "log" ? " active" : ""}`}
                  href={`/${repoNav.name}/log/`}
                >
                  log
                </a>
              </li>
            </ul>
          </nav>
        ) : null}
      </div>
    </header>
  );
}

export const renderer = jsxRenderer(
  ({ children, repoNav }: PropsWithChildren<{ repoNav?: RepoNav }>) => (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/terminal.min.css" />
        <link rel="stylesheet" href="/cgit.css" />
      </head>
      <body>
        <div class="container">
          <Header repoNav={repoNav} />
          <main>{children}</main>
          <hr />
          <footer>
            <p>generated by cgit-ts</p>
          </footer>
        </div>
      </body>
    </html>
  ),
);
