import { jsxRenderer, useRequestContext } from "hono/jsx-renderer";

// Root document chrome, wrapping every page's content.
export const renderer = jsxRenderer(({ children }) => (
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="stylesheet" href="/terminal.min.css" />
      <link rel="stylesheet" href="/cgit.css" />
    </head>
    <body>
      <div class="container">
        <header>
          <div class="terminal-nav">
            <div class="terminal-logo">
              <div class="logo terminal-prompt">
                <a href="/">cgit-ts</a>
              </div>
            </div>
          </div>
        </header>
        <main>{children}</main>
        <hr />
        <footer>
          <p>generated by cgit-ts</p>
        </footer>
      </div>
    </body>
  </html>
));

// Per-repo menu. Reads the repo and the active page straight off the request
// context, so handlers never thread navigation state through render props.
function RepoNav() {
  const c = useRequestContext();
  // No repo resolved (e.g. an error or 404 under /:repo/*): skip the menu.
  const disc = c.get("disc");
  if (!disc) return null;
  const name = disc.name;
  const path = c.req.path;
  const active =
    path.includes("/tree/") || path.includes("/raw/")
      ? "tree"
      : path.endsWith("/log/")
        ? "log"
        : "summary";
  const item = (page: "summary" | "log" | "tree", href: string) => (
    <li>
      <a class={`menu-item${active === page ? " active" : ""}`} href={href}>
        {page}
      </a>
    </li>
  );
  return (
    <nav class="terminal-menu">
      <ul>
        {item("summary", `/${name}/`)}
        {item("log", `/${name}/log/`)}
        {item("tree", `/${name}/tree/`)}
      </ul>
    </nav>
  );
}

// Nested layout for repo pages: wraps the parent chrome and prepends the menu.
export const repoLayout = jsxRenderer(({ children, Layout }) => (
  <Layout>
    <RepoNav />
    {children}
  </Layout>
));
